### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by dreamcenter** [Zxilly/JobInformationAggregation#1]
你是如何通过它的登陆验证从而获得cookie的

**Comment by Zxilly** [comment]
额
https://github.com/Zxilly/JobInformationAggregation/blob/ee4a04a509627ee32280bb993758727edf6832f8/func.py#L20-L61
主要是这段的逻辑，我找到了一个超星官网用学习通客户端扫码登陆的接口，在https://passport2.chaoxing.com/login?fid=&newversion=true
主要是newversion这个参数，没这个参数是没有扫码登陆的

**Comment by dreamcenter** [comment]
嗯，ok了，谢谢
